/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;

import BUS.NhanVienBUS;
import BUS.PhanQuyenBUS;
import BUS.TaiKhoanBUS;
import Custom.MyDialog;
import Custom.Utils;
import Model.NhanVien;
import Model.PhanQuyen;
import Model.TaiKhoan;
import java.awt.Dialog;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.border.SoftBevelBorder;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Nun-PC
 */
public class PnQuanLyNhanVienGUI extends javax.swing.JPanel {

    /**
     * Creates new form PnNhanVien
     */
    public PnQuanLyNhanVienGUI() {
        initComponents();
        addControls();
        loadData();
    }
    public void loadData(){
        PhanQuyenBUS phanQuyenBUS = new PhanQuyenBUS();
        ArrayList<PhanQuyen> listQuyen = phanQuyenBUS.getListQuyen();
        cbChucVu.removeAllItems();
        for (PhanQuyen pq: listQuyen){
            cbChucVu.addItem(pq.getQuyen());
        }
        loadDSNhanVien();
        loadNhomQuyen();
    }
    public void loadDSNhanVien(){
        NhanVienBUS nvbus = new NhanVienBUS();
        TaiKhoanBUS tkbus = new TaiKhoanBUS();
        ArrayList<NhanVien> listNV = nvbus.getDanhSachNhanVien();
        DefaultTableModel model = (DefaultTableModel)tblNhanVien.getModel();
        model.setRowCount(0);
        for (NhanVien nv: listNV){
            String tendangnhaptaikhoan = "";
            tendangnhaptaikhoan = tkbus.getTenDangNhapByMaNV(String.valueOf(nv.getMaNV()));
            model.addRow(new Object[]{nv.getMaNV(), nv.getHo(), nv.getTen(), nv.getGioiTinh(), nv.getChucVu(), tendangnhaptaikhoan});
        }
    }
    public void loadNhomQuyen(){
        PhanQuyenBUS pqbus = new PhanQuyenBUS();
        ArrayList<PhanQuyen> listPQ =  pqbus.getListQuyen();
        DefaultTableModel model = (DefaultTableModel)tblNhomQuyen.getModel();
        model.setRowCount(0);
        for (PhanQuyen pq: listPQ){
            model.addRow(new Object[]{pq.getQuyen()});
        }
    }
    private void addControls(){
        Utils.customTable(tblNhanVien);
//        Utils.customTable(tblQuyen);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnThem = new javax.swing.JLabel();
        btnSua = new javax.swing.JLabel();
        btnXoa = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtMaNhanVien = new javax.swing.JTextField();
        txtTen = new javax.swing.JTextField();
        txtHoDem = new javax.swing.JTextField();
        cbGioiTinh = new javax.swing.JComboBox<>();
        btnCapTaiKhoan = new javax.swing.JLabel();
        btnDatLaiMatKhau = new javax.swing.JLabel();
        btnKhoaTaiKhoan = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblNhanVien = new javax.swing.JTable();
        cbChucVu = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        ckbNhapHang = new javax.swing.JCheckBox();
        ckbThongKe = new javax.swing.JCheckBox();
        ckbSanPham = new javax.swing.JCheckBox();
        ckbKhachHang = new javax.swing.JCheckBox();
        ckbNhanVien = new javax.swing.JCheckBox();
        btnThemQuyen = new javax.swing.JLabel();
        btnSuaQuyen = new javax.swing.JLabel();
        btnXoaQuyen = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblNhomQuyen = new javax.swing.JTable();
        txtNhomQuyen = new javax.swing.JTextField();

        jTabbedPane1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTabbedPane1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jTabbedPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTabbedPane1MouseClicked(evt);
            }
        });

        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel1MouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 28)); // NOI18N
        jLabel1.setText("QUẢN LÝ NHÂN VIÊN");

        btnThem.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnThem.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        btnThem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/add.png"))); // NOI18N
        btnThem.setText(" Thêm  ");
        btnThem.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnThem.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnThem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnThemMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnThemMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnThemMouseExited(evt);
            }
        });

        btnSua.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnSua.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        btnSua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/pencil.png"))); // NOI18N
        btnSua.setText("   Sửa   ");
        btnSua.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnSua.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnSua.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSuaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSuaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSuaMouseExited(evt);
            }
        });

        btnXoa.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnXoa.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        btnXoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/clear.png"))); // NOI18N
        btnXoa.setText("   Xóa   ");
        btnXoa.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnXoa.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnXoa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnXoaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnXoaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnXoaMouseExited(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Họ đệm");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("Mã nhân viên");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setText("Tên");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel8.setText("Giới tính");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel9.setText("Chức vụ");

        txtMaNhanVien.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N

        txtTen.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N

        txtHoDem.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N

        cbGioiTinh.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        cbGioiTinh.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nam", "Nữ", " " }));

        btnCapTaiKhoan.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnCapTaiKhoan.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        btnCapTaiKhoan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/add-user.png"))); // NOI18N
        btnCapTaiKhoan.setText("  Cấp tài khoản   ");
        btnCapTaiKhoan.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnCapTaiKhoan.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnCapTaiKhoan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCapTaiKhoanMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCapTaiKhoanMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCapTaiKhoanMouseExited(evt);
            }
        });

        btnDatLaiMatKhau.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnDatLaiMatKhau.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        btnDatLaiMatKhau.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/password-code.png"))); // NOI18N
        btnDatLaiMatKhau.setText("Đặt Lại Mật Khẩu");
        btnDatLaiMatKhau.setToolTipText("");
        btnDatLaiMatKhau.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnDatLaiMatKhau.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnDatLaiMatKhau.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDatLaiMatKhauMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnDatLaiMatKhauMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnDatLaiMatKhauMouseExited(evt);
            }
        });

        btnKhoaTaiKhoan.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnKhoaTaiKhoan.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        btnKhoaTaiKhoan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/log-in.png"))); // NOI18N
        btnKhoaTaiKhoan.setText(" Khóa tài khoản  ");
        btnKhoaTaiKhoan.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnKhoaTaiKhoan.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnKhoaTaiKhoan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnKhoaTaiKhoanMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnKhoaTaiKhoanMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnKhoaTaiKhoanMouseExited(evt);
            }
        });

        tblNhanVien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã nhân viên", "Họ đệm", "Tên", "Giới tính", "Chức vụ", "Tài khoản"
            }
        ));
        tblNhanVien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblNhanVienMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblNhanVien);
        if (tblNhanVien.getColumnModel().getColumnCount() > 0) {
            tblNhanVien.getColumnModel().getColumn(1).setResizable(false);
            tblNhanVien.getColumnModel().getColumn(1).setHeaderValue("Họ đệm");
            tblNhanVien.getColumnModel().getColumn(2).setHeaderValue("Tên");
            tblNhanVien.getColumnModel().getColumn(3).setHeaderValue("Giới tính");
            tblNhanVien.getColumnModel().getColumn(4).setResizable(false);
            tblNhanVien.getColumnModel().getColumn(4).setHeaderValue("Chức vụ");
            tblNhanVien.getColumnModel().getColumn(5).setHeaderValue("Tài khoản");
        }

        cbChucVu.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(166, 166, 166)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(105, 105, 105)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel5)
                                            .addComponent(jLabel8)
                                            .addComponent(jLabel9))
                                        .addGap(82, 82, 82)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(txtMaNhanVien, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtHoDem, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtTen, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(cbGioiTinh, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(cbChucVu, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(btnCapTaiKhoan, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(36, 36, 36)
                                                .addComponent(btnDatLaiMatKhau, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(86, 86, 86)
                                                .addComponent(btnSua, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(37, 37, 37)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(btnKhoaTaiKhoan, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(354, 354, 354)
                                .addComponent(jLabel1)))
                        .addGap(0, 170, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1)
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtMaNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtHoDem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtTen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(cbGioiTinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(cbChucVu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSua, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCapTaiKhoan, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDatLaiMatKhau, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnKhoaTaiKhoan, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 362, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Nhân viên", jPanel1);

        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel2MouseClicked(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 28)); // NOI18N
        jLabel4.setText("QUẢN LÝ PHÂN QUYỀN");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setText("Nhóm quyền");

        ckbNhapHang.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        ckbNhapHang.setText("Quản lý nhập hàng");

        ckbThongKe.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        ckbThongKe.setText("Quản lý thống kê");

        ckbSanPham.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        ckbSanPham.setText("Quản lý sản phẩm");

        ckbKhachHang.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        ckbKhachHang.setText("Quản lý khách hàng");

        ckbNhanVien.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        ckbNhanVien.setText("Quản lý nhân viên");

        btnThemQuyen.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnThemQuyen.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        btnThemQuyen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/add.png"))); // NOI18N
        btnThemQuyen.setText(" Thêm quyền  ");
        btnThemQuyen.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnThemQuyen.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnThemQuyen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnThemQuyenMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnThemQuyenMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnThemQuyenMouseExited(evt);
            }
        });
        btnThemQuyen.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnThemQuyenKeyPressed(evt);
            }
        });

        btnSuaQuyen.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnSuaQuyen.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        btnSuaQuyen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/pencil.png"))); // NOI18N
        btnSuaQuyen.setText("  Sửa quyền    ");
        btnSuaQuyen.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnSuaQuyen.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnSuaQuyen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSuaQuyenMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSuaQuyenMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSuaQuyenMouseExited(evt);
            }
        });

        btnXoaQuyen.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnXoaQuyen.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        btnXoaQuyen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/clear.png"))); // NOI18N
        btnXoaQuyen.setText("   Xóa quyền   ");
        btnXoaQuyen.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnXoaQuyen.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnXoaQuyen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnXoaQuyenMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnXoaQuyenMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnXoaQuyenMouseExited(evt);
            }
        });

        tblNhomQuyen.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Quyền"
            }
        ));
        tblNhomQuyen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblNhomQuyenMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblNhomQuyen);
        if (tblNhomQuyen.getColumnModel().getColumnCount() > 0) {
            tblNhomQuyen.getColumnModel().getColumn(0).setResizable(false);
        }

        txtNhomQuyen.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(125, 125, 125)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ckbSanPham)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(ckbNhapHang)
                                        .addGap(79, 79, 79)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(ckbNhanVien)
                                            .addComponent(ckbThongKe)
                                            .addComponent(ckbKhachHang))))
                                .addGap(99, 99, 99))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addComponent(jLabel6)
                                .addGap(18, 18, 18)
                                .addComponent(txtNhomQuyen)
                                .addGap(115, 115, 115)))
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(226, 226, 226)
                        .addComponent(btnThemQuyen, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnSuaQuyen, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnXoaQuyen, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(334, 334, 334)
                        .addComponent(jLabel4)))
                .addContainerGap(126, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(jLabel4)
                .addGap(159, 159, 159)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txtNhomQuyen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ckbNhapHang)
                            .addComponent(ckbNhanVien))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ckbSanPham)
                            .addComponent(ckbKhachHang))
                        .addGap(18, 18, 18)
                        .addComponent(ckbThongKe))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThemQuyen, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSuaQuyen, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnXoaQuyen, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(278, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Quyền", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1030, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnThemMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnThemMouseEntered
        btnThem.setBorder(new SoftBevelBorder(SoftBevelBorder.LOWERED));
    }//GEN-LAST:event_btnThemMouseEntered

    private void btnThemMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnThemMouseExited
        btnThem.setBorder(new SoftBevelBorder(SoftBevelBorder.RAISED));
    }//GEN-LAST:event_btnThemMouseExited

    private void btnSuaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSuaMouseEntered
        btnSua.setBorder(new SoftBevelBorder(SoftBevelBorder.LOWERED));
    }//GEN-LAST:event_btnSuaMouseEntered

    private void btnSuaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSuaMouseExited
        btnSua.setBorder(new SoftBevelBorder(SoftBevelBorder.RAISED));
    }//GEN-LAST:event_btnSuaMouseExited

    private void btnXoaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnXoaMouseEntered
        btnXoa.setBorder(new SoftBevelBorder(SoftBevelBorder.LOWERED));
    }//GEN-LAST:event_btnXoaMouseEntered

    private void btnXoaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnXoaMouseExited
        btnXoa.setBorder(new SoftBevelBorder(SoftBevelBorder.RAISED));
    }//GEN-LAST:event_btnXoaMouseExited

    private void btnCapTaiKhoanMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCapTaiKhoanMouseEntered
        btnCapTaiKhoan.setBorder(new SoftBevelBorder(SoftBevelBorder.LOWERED));
    }//GEN-LAST:event_btnCapTaiKhoanMouseEntered

    private void btnCapTaiKhoanMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCapTaiKhoanMouseExited
        btnCapTaiKhoan.setBorder(new SoftBevelBorder(SoftBevelBorder.RAISED));
    }//GEN-LAST:event_btnCapTaiKhoanMouseExited

    private void btnDatLaiMatKhauMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDatLaiMatKhauMouseEntered
        btnDatLaiMatKhau.setBorder(new SoftBevelBorder(SoftBevelBorder.LOWERED));
    }//GEN-LAST:event_btnDatLaiMatKhauMouseEntered

    private void btnDatLaiMatKhauMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDatLaiMatKhauMouseExited
        btnDatLaiMatKhau.setBorder(new SoftBevelBorder(SoftBevelBorder.RAISED));
    }//GEN-LAST:event_btnDatLaiMatKhauMouseExited

    private void btnKhoaTaiKhoanMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnKhoaTaiKhoanMouseEntered
        btnKhoaTaiKhoan.setBorder(new SoftBevelBorder(SoftBevelBorder.LOWERED));
    }//GEN-LAST:event_btnKhoaTaiKhoanMouseEntered

    private void btnKhoaTaiKhoanMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnKhoaTaiKhoanMouseExited
        btnKhoaTaiKhoan.setBorder(new SoftBevelBorder(SoftBevelBorder.RAISED));
    }//GEN-LAST:event_btnKhoaTaiKhoanMouseExited

    private void btnThemQuyenMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnThemQuyenMouseEntered
        btnThemQuyen.setBorder(new SoftBevelBorder(SoftBevelBorder.LOWERED));
    }//GEN-LAST:event_btnThemQuyenMouseEntered

    private void btnThemQuyenMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnThemQuyenMouseExited
        btnThemQuyen.setBorder(new SoftBevelBorder(SoftBevelBorder.RAISED));
    }//GEN-LAST:event_btnThemQuyenMouseExited

    private void btnSuaQuyenMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSuaQuyenMouseEntered
        btnSuaQuyen.setBorder(new SoftBevelBorder(SoftBevelBorder.LOWERED));
    }//GEN-LAST:event_btnSuaQuyenMouseEntered

    private void btnSuaQuyenMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSuaQuyenMouseExited
        btnSuaQuyen.setBorder(new SoftBevelBorder(SoftBevelBorder.RAISED));
    }//GEN-LAST:event_btnSuaQuyenMouseExited

    private void btnXoaQuyenMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnXoaQuyenMouseEntered
        btnXoaQuyen.setBorder(new SoftBevelBorder(SoftBevelBorder.LOWERED));
    }//GEN-LAST:event_btnXoaQuyenMouseEntered

    private void btnXoaQuyenMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnXoaQuyenMouseExited
        btnXoaQuyen.setBorder(new SoftBevelBorder(SoftBevelBorder.RAISED));
    }//GEN-LAST:event_btnXoaQuyenMouseExited

    private void btnThemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnThemMouseClicked
        String ma = txtMaNhanVien.getText().toString();
        int manv = -1;
        try {
            manv = Integer.parseInt(ma);
        } catch (Exception e) {
            new MyDialog("Mã nhân viên chỉ gồm chứ số", MyDialog.ERROR_DIALOG);
        }
        String ho = txtHoDem.getText().toString();
        String ten = txtTen.getText().toString();
        String gioitinh = cbGioiTinh.getSelectedItem().toString();
        String chucvu = cbChucVu.getSelectedItem().toString();
        NhanVienBUS nvbus = new NhanVienBUS();
        nvbus.themNhanVien(manv, ho, ten, gioitinh, chucvu);
        loadDSNhanVien();
        clear();
    }//GEN-LAST:event_btnThemMouseClicked

    private void btnXoaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnXoaMouseClicked
        NhanVienBUS nvbus = new NhanVienBUS();
        String manv = txtMaNhanVien.getText();
        try {
            int ma = Integer.parseInt(manv);
            nvbus.deleteNhanVien_xoamem(ma);
        } catch (Exception e) {
        }
        loadDSNhanVien();
        clear();
    }//GEN-LAST:event_btnXoaMouseClicked

    private void tblNhanVienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblNhanVienMouseClicked
        String manv = tblNhanVien.getValueAt(tblNhanVien.getSelectedRow(), 0).toString();
        String ho = tblNhanVien.getValueAt(tblNhanVien.getSelectedRow(), 1).toString();
        String ten = tblNhanVien.getValueAt(tblNhanVien.getSelectedRow(), 2).toString();
        String gioitinh = tblNhanVien.getValueAt(tblNhanVien.getSelectedRow(), 3).toString();
        String chucvu = tblNhanVien.getValueAt(tblNhanVien.getSelectedRow(), 4).toString();
        txtMaNhanVien.setText(manv);
        txtHoDem.setText(ho);
        txtTen.setText(ten);
        cbChucVu.setSelectedItem(chucvu);
        cbGioiTinh.setSelectedItem(gioitinh);
    }//GEN-LAST:event_tblNhanVienMouseClicked

    private void jPanel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseClicked
        clear();
    }//GEN-LAST:event_jPanel1MouseClicked

    private void btnSuaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSuaMouseClicked
        String manv = txtMaNhanVien.getText().toString();
        if (manv.equals("")){
            new MyDialog("Chưa chọn nhân viên!", MyDialog.ERROR_DIALOG);
        }
        String ho = txtHoDem.getText().toString();
        String ten = txtTen.getText().toString();
        String gioitinh = cbGioiTinh.getSelectedItem().toString();
        String chucvu = cbChucVu.getSelectedItem().toString();
        NhanVienBUS nvbus = new NhanVienBUS();
        nvbus.updateNhanVien(manv, ho, ten, gioitinh, chucvu);
        loadDSNhanVien();
        clear();
    }//GEN-LAST:event_btnSuaMouseClicked

    private void btnCapTaiKhoanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCapTaiKhoanMouseClicked
        String taikhoan = tblNhanVien.getValueAt(tblNhanVien.getSelectedRow(), 5).toString();
        if (taikhoan.equals("")){
            String manv = txtMaNhanVien.getText().toString();
            DlgCapTaiKhoan dlgCapTaiKhoan = new DlgCapTaiKhoan(manv);
            dlgCapTaiKhoan.setVisible(true);
            loadDSNhanVien();
        }
        else{
            new MyDialog("Nhân viên này đã có tài khoản!", MyDialog.ERROR_DIALOG);
        }
    }//GEN-LAST:event_btnCapTaiKhoanMouseClicked

    private void btnThemQuyenKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnThemQuyenKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnThemQuyenKeyPressed

    private void btnThemQuyenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnThemQuyenMouseClicked
        PhanQuyenBUS pqbus = new PhanQuyenBUS();
        String quyen = txtNhomQuyen.getText();
        if (quyen.equals("")){
            new MyDialog("Chưa chọn quyền !", MyDialog.ERROR_DIALOG);
        }
        int qlnhaphang = ckbNhapHang.isSelected() ? 1 : 0;
        int qlsanpham = ckbSanPham.isSelected() ? 1 : 0;
        int qlnhanvien = ckbNhanVien.isSelected() ? 1 : 0;
        int qlkhachhang = ckbKhachHang.isSelected() ? 1 : 0;
        int qlthongke = ckbThongKe.isSelected() ? 1 : 0;
        PhanQuyen pq = new PhanQuyen(quyen, qlnhaphang, qlsanpham, qlnhanvien, qlkhachhang, qlthongke);
        pqbus.addQuyen(pq);
        clearCkb();
        loadData();
    }//GEN-LAST:event_btnThemQuyenMouseClicked

    private void jTabbedPane1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabbedPane1MouseClicked

    }//GEN-LAST:event_jTabbedPane1MouseClicked

    private void btnXoaQuyenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnXoaQuyenMouseClicked
        PhanQuyenBUS pqbus = new PhanQuyenBUS();
        String quyen = txtNhomQuyen.getText().toString();
        if (quyen.equals("")){
            new MyDialog("Chưa chọn quyền !", MyDialog.ERROR_DIALOG);
        }else{
            pqbus.deleteQuyen(quyen);
            clearCkb();
            loadData();
        }
    }//GEN-LAST:event_btnXoaQuyenMouseClicked

    private void tblNhomQuyenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblNhomQuyenMouseClicked
        clearCkb();
        String quyen = tblNhomQuyen.getValueAt(tblNhomQuyen.getSelectedRow(), 0).toString();
        txtNhomQuyen.setText(quyen);
        PhanQuyenBUS pqbus = new PhanQuyenBUS();
        PhanQuyen pq = pqbus.getPhanQuyen(quyen);
        if (pq.getNhapHang() == 1){ckbNhapHang.setSelected(true);}
        if (pq.getQlSanPham() == 1){ckbSanPham.setSelected(true);}
        if (pq.getQlNhanVien() == 1){ckbNhanVien.setSelected(true);}
        if (pq.getQlKhachHang() == 1){ckbKhachHang.setSelected(true);}
        if (pq.getThongKe() == 1){ckbThongKe.setSelected(true);}
    }//GEN-LAST:event_tblNhomQuyenMouseClicked

    private void jPanel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseClicked
        clearCkb();
    }//GEN-LAST:event_jPanel2MouseClicked

    private void btnSuaQuyenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSuaQuyenMouseClicked
        PhanQuyenBUS pqbus = new PhanQuyenBUS();
        String quyen = txtNhomQuyen.getText();
        ArrayList<PhanQuyen> list = pqbus.getListQuyen();
        if (quyen.equals("")){
            new MyDialog("Chưa chọn quyền !", MyDialog.ERROR_DIALOG);
        }
        boolean flag = false;
        for (PhanQuyen pq: list){
            if (pq.getQuyen().toString().equals(quyen)){
                flag = true;
            }
        }
        if (flag){
            int qlnhaphang = ckbNhapHang.isSelected() ? 1 : 0;
            int qlsanpham = ckbSanPham.isSelected() ? 1 : 0;
            int qlnhanvien = ckbNhanVien.isSelected() ? 1 : 0;
            int qlkhachhang = ckbKhachHang.isSelected() ? 1 : 0;
            int qlthongke = ckbThongKe.isSelected() ? 1 : 0;
            PhanQuyen pq = new PhanQuyen(quyen, qlnhaphang, qlsanpham, qlnhanvien, qlkhachhang, qlthongke);
            pqbus.updateQuyen(pq);
            clearCkb();
            loadData();
        }else{
            new MyDialog("Không tìm thấy quyền muốn cập nhật!", MyDialog.ERROR_DIALOG);
        }
        
    }//GEN-LAST:event_btnSuaQuyenMouseClicked

    private void btnKhoaTaiKhoanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnKhoaTaiKhoanMouseClicked
        String taikhoan = tblNhanVien.getValueAt(tblNhanVien.getSelectedRow(), 5).toString();
        if (taikhoan.equals("")){
            new MyDialog("Nhân viên này chưa có tài khoản!", MyDialog.ERROR_DIALOG);
        }
        else{
            TaiKhoanBUS tkBus = new TaiKhoanBUS();
            String maNV = txtMaNhanVien.getText().toString();
            if (maNV.equals("")){
                new MyDialog("Chưa chọn nhân viên!", MyDialog.ERROR_DIALOG);
            }else{
                int manv = Integer.parseInt(txtMaNhanVien.getText().toString());
                boolean flag = tkBus.khoaTaiKhoan(manv);
                if (flag){
                    new MyDialog("Đã khóa tài khoản!", MyDialog.SUCCESS_DIALOG);
                    loadData();
                }else{
                    new MyDialog("Error!", MyDialog.ERROR_DIALOG);
                }
            }
            
        }
    }//GEN-LAST:event_btnKhoaTaiKhoanMouseClicked

    private void btnDatLaiMatKhauMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDatLaiMatKhauMouseClicked
        String taikhoan = tblNhanVien.getValueAt(tblNhanVien.getSelectedRow(), 5).toString();
        if (taikhoan.equals("")){
            new MyDialog("Nhân viên này chưa có tài khoản!", MyDialog.ERROR_DIALOG);
        }
        else{
            String manv = txtMaNhanVien.getText().toString();
            if (manv.equals("")){
                new MyDialog("Chưa chọn tài khoản!", MyDialog.ERROR_DIALOG);
            }else{
                int maNV = Integer.parseInt(manv);
                TaiKhoanBUS tkbus = new TaiKhoanBUS();
                TaiKhoan tk = tkbus.getTaiKhoan_DatLaiMatKhau(maNV);
                String tendangnhap = tk.getTenDangNhap();
                tkbus.datLaiMatKhau(manv, tendangnhap);
                new MyDialog("Đã đặt lại mật khẩu là "+tendangnhap+"", MyDialog.SUCCESS_DIALOG);
            }
        }
    }//GEN-LAST:event_btnDatLaiMatKhauMouseClicked
    public void clearCkb(){
        txtNhomQuyen.setText("");
        ckbNhapHang.setSelected(false);
        ckbNhanVien.setSelected(false);
        ckbSanPham.setSelected(false);
        ckbKhachHang.setSelected(false);
        ckbThongKe.setSelected(false);
    }
    public void clear(){
        txtMaNhanVien.setText("");
        txtHoDem.setText("");
        txtTen.setText("");
        cbChucVu.setSelectedIndex(0);
        cbGioiTinh.setSelectedIndex(0);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnCapTaiKhoan;
    private javax.swing.JLabel btnDatLaiMatKhau;
    private javax.swing.JLabel btnKhoaTaiKhoan;
    private javax.swing.JLabel btnSua;
    private javax.swing.JLabel btnSuaQuyen;
    private javax.swing.JLabel btnThem;
    private javax.swing.JLabel btnThemQuyen;
    private javax.swing.JLabel btnXoa;
    private javax.swing.JLabel btnXoaQuyen;
    private javax.swing.JComboBox<String> cbChucVu;
    private javax.swing.JComboBox<String> cbGioiTinh;
    private javax.swing.JCheckBox ckbKhachHang;
    private javax.swing.JCheckBox ckbNhanVien;
    private javax.swing.JCheckBox ckbNhapHang;
    private javax.swing.JCheckBox ckbSanPham;
    private javax.swing.JCheckBox ckbThongKe;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable tblNhanVien;
    private javax.swing.JTable tblNhomQuyen;
    private javax.swing.JTextField txtHoDem;
    private javax.swing.JTextField txtMaNhanVien;
    private javax.swing.JTextField txtNhomQuyen;
    private javax.swing.JTextField txtTen;
    // End of variables declaration//GEN-END:variables
}

